[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
bictory_test = "ECVESb2kpEyN3WoQU1ZvVt51SjBa2wUccZJ5PGJcoqHr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
